x=read.delim("scores.tsv",head=T)
x[[1]]=as.logical(x[[1]])
x[[2]]=as.character(x[[2]])
for (i in 3:ncol(x)) x[[i]] = as.numeric(gsub('f0','',as.character(x[[i]])))
xx=subset(x,is_row_col=='r')
## par(mfrow=c(3,3))
## hist((xx$score-mean(xx$score,na.rm=T))/sd(xx$score,na.rm=T),breaks=50)
## hist((xx$score_n-mean(xx$score_n,na.rm=T))/sd(xx$score_n,na.rm=T),breaks=50)
## hist((xx$score_m-mean(xx$score_m,na.rm=T))/sd(xx$score_m,na.rm=T),breaks=50)
## hist((xx$score_v-mean(xx$score_v,na.rm=T))/sd(xx$score_v,na.rm=T),breaks=50)
## hist((xx$score_g-mean(xx$score_g,na.rm=T))/sd(xx$score_g,na.rm=T),breaks=50)
## hist((xx$combined-mean(xx$combined,na.rm=T))/sd(xx$combined,na.rm=T),breaks=50)
par(mfrow=c(3,3))
hist((xx$score)/sd(xx$score,na.rm=T),breaks=50)
hist((xx$score_n)/sd(xx$score_n,na.rm=T),breaks=50)
hist((xx$score_m)/sd(xx$score_m,na.rm=T),breaks=50)
hist((xx$score_v)/sd(xx$score_v,na.rm=T),breaks=50)
hist((xx$score_g)/sd(xx$score_g,na.rm=T),breaks=50)
hist((xx$combined)/sd(xx$combined,na.rm=T),breaks=50)
